Render edits
jbatoast/CRS-Scheduler pull request #11
Opened 2023-06-07 15:23 UTC by Koniiro

2023-06-08 06:36 UTC, eyronjuude commented on backend/CourseParser.py
`match` did not work in render?

2023-06-08 06:41 UTC, eyronjuude requested changes
Code is ok, but I noticed some changes in the backend that caught up my attention.

Kindly check the posted review comments in the affected files.

2023-06-08 06:41 UTC, eyronjuude commented on backend/CourseParser.py
`match` did not work in render?

2023-06-08 06:41 UTC, eyronjuude commented on backend/app.py
Use the updated `server.py` in `main` and try to integrate the said file to render.

Or you could just rename the `server.py` in `main` as `app.py` — your choice.

2023-06-08 07:03 UTC, Koniiro commented on backend/CourseParser.py
yes di siya nagwowork sa render apparently. like when i checked the logs. yung match yung specifically na mention niya

2023-06-08 08:00 UTC, eyronjuude commented on backend/CourseParser.py
Okay noted.

2023-06-08 10:46 UTC, Koniiro commented on backend/app.py
i dont see any differences with server and app pero yung need ni render is yung app.py so ill keep it as is

2023-06-08 13:05 UTC, eyronjuude commented on backend/app.py
Resolved from 911f21a.

2023-06-09 06:04 UTC, eyronjuude approved these changes

2023-06-09 06:17 UTC, eyronjuude commented
@Koniiro can you pull this branch forcefully then check the deployment status?

Apparently it failed the necessary checks after I resolved the merge conflicts. Please acknowledge.

Thanks.

2023-06-09 06:26 UTC, eyronjuude commented
Nevermind. Sorry for the ping. I think I made a mistake in solving merge conflicts.

Gotta try fixing the commit history once more.

2023-06-09 15:41 UTC, merged